openapi: 3.1.1
info:
  title: Metafy API
  version: v1
  contact:
    name: Metafy
    url: https://metafy.gg
    email: engineering@metafy.gg

servers:
  - url: https://metafy.gg/irk/api
    description: API Endpoint

security:
  - authorizationCode: []
  - clientCredentials: []
  - apiKeys: []

# Tags for organizing endpoints into categories
tags:
  - name: User
    description: Operations related to the authenticated users profile information
  - name: Community
    description: Operations related to the authenticated users community
  - name: Products
    description: Operations related to the product offerings of the authenticated user
  - name: Purchases
    description: Operations for verifying purchases and subscriptions

paths:
  /v1/me:
    get:
      tags:
        - User
      summary: Get Profile
      description: |
        This endpoint returns information about the authenticated account.
      operationId: getMe
      security:
        - authorizationCode: [profile]
        - clientCredentials: [profile]
        - apiKeys: [profile]
  /v1/me/sessions:
    get:
      tags:
        - Products
      summary: List Sessions
      description: |
        This endpoint returns a list of sessions that the authenticated account has on offer.
      operationId: getSessions
      security:
        - authorizationCode: [products]
        - clientCredentials: [products]
        - apiKeys: [products]
  /v1/me/events:
    get:
      tags:
        - Products
      summary: List Events
      description: |
        This endpoint returns a list of events that the authenticated account has on offer.
      operationId: getEvents
      security:
        - authorizationCode: [products]
        - clientCredentials: [products]
        - apiKeys: [products]
  /v1/me/guides:
    get:
      tags:
        - Products
      summary: List Guides
      description: |
        This endpoint returns a list of guides that the authenticated account has published.
      operationId: getMyGuides
      security:
        - authorizationCode: [products]
        - clientCredentials: [products]
        - apiKeys: [products]
  /v1/me/community:
    get:
      tags:
        - Community
      summary: Get Community
      description: |
        This endpoint returns information about the commmunity owned by the authenticated account.
      operationId: getMyCommunity
      security:
        - authorizationCode: [community]
        - clientCredentials: [community]
        - apiKeys: [community]
  /v1/me/community/subscribers:
    get:
      tags:
        - Community
      summary: List Community Subscribers
      description: |
        This endpoint returns a paginated list of active subscribers to the authenticated account's community.
      operationId: getMyCommunitySubscribers
      security:
        - authorizationCode: [community]
        - clientCredentials: [community]
        - apiKeys: [commmunity]
  /v1/me/community/members:
    get:
      tags:
        - Community
      summary: List Community Members
      description: |
        This endpoint returns a paginated list of all members of the authenticated account's community.
      operationId: getCommunityMembers
      security:
        - authorizationCode: [community]
        - clientCredentials: [community]
        - apiKeys: [community]
  /v1/me/community/members/{userIdOrSlug}:
    get:
      tags:
        - Community
      summary: Get Community Member
      description: |
        This endpoint returns information on a community member if they exist.
      operationId: getCommunityMember
      security:
        - authorizationCode: [community]
        - clientCredentials: [community]
        - apiKeys: [community]
  /v1/me/community/team/sessions:
    get:
      tags:
        - Community
      summary: List Team Sessions
      description: |
        This endpoint returns a list of sessions that members of your team have shared with your community.
      operationId: getCommunityTeamSessions
      security:
        - authorizationCode: [community]
        - clientCredentials: [community]
        - apiKeys: [community]
  /v1/me/community/team/events:
    get:
      tags:
        - Community
      summary: List Team Events
      description: |
        This endpoint returns a list of events that members of your team have shared with your community.
      operationId: getCommunityTeamEvents
      security:
        - authorizationCode: [community]
        - clientCredentials: [community]
        - apiKeys: [community]
  /v1/me/community/team/guides:
    get:
      tags:
        - Community
      summary: List Team Guides
      description: |
        This endpoint returns a list of guides that members of your team have shared with your community.
      operationId: getCommunityTeamGuides
      security:
        - authorizationCode: [community]
        - clientCredentials: [community]
        - apiKeys: [community]
  /v1/me/purchases/guides/{guideId}:
    get:
      tags:
        - Purchases
      summary: Purchased Guide
      description: |
        This endpoint determines if the authenticated account has access to read this guide.

        This could be from a purchase of the guide or from an active subscription benefit.
      operationId: checkGuideAccess
      security:
        - authorizationCode: [purchases]
        - clientCredentials: [purchases]
        - apiKeys: [purchases]
  /v1/me/purchases/communities/{communityId}:
    get:
      tags:
        - Purchases
      summary: Purchased Subscription
      description: |
        This endpoint determines if the authenticated account has an active subscription to this community.
      operationId: checkCommunitySubscription
      security:
        - authorizationCode: [purchases]
        - clientCredentials: [purchases]
        - apiKeys: [purchases]
components:
  securitySchemes:
    clientCredentials:
      type: oauth2
      description: |
        This API uses OAuth 2 with the client credentials flow.

        You must pass in your `client_id` to the `Authorization` header using `Bearer`.
      flows:
        clientCredentials:
          tokenUrl: https://metafy.gg/irk/oauth/token
          scopes:
            profile: Access to the users basic profile information including email
            community: Access to users community, including member and subscriber details
            content: Access to products offered by the user on Metafy
            purchases: Verify purchases of the user
    authorizationCode:
      type: oauth2
      description: |
        This API uses OAuth 2 with the authorization code flow.

        You must pass in your `client_id` to the `Authorization` header using `Bearer`.
      flows:
        authorizationCode:
          authorizationUrl: https://metafy.gg/auth/authorize
          tokenUrl: https://metafy.gg/irk/oauth/token
          refreshUrl: https://metafy.gg/irk/oauth/token
          scopes:
            profile: Access to the users basic profile information including email
            community: Access to users community, including member and subscriber details
            content: Access to products offered by the user on Metafy
            purchases: Verify purchases of the user
    apiKeys:
      type: http
      description: |
        This uses API keys as the authorization method.

        You can pass in your API key to the `Authorization` header using `Bearer` or you can pass it as a query param `api_key`.
      scheme: bearer
